# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9b685c57f8e8d8aed9cf76fb6ea0ce3fe86d37d3910bbb27e6a2fbb0170cd7b174c3a2f5087ae8dc3faebc121e52fa4155b167efc9d373450190603d7f869e9

test:
  secret_key_base: 1416706b48e19673b13cc098cb8faaffb285a6f5687f6bdfb06550af31e234696213dc3d4ef99a9aa1cec2577bbf5fb39dd01535b785f840c7461c739c9b2906

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
